config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :pictures
  end

  root :to => "home#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user

  has_attached_file :picture, :styles => { :medium => '300x300>', :thumb => '100x100>' }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pictures, :dependent => :destroy
   has_attached_file :avatar, :styles => { :medium => '300x300>', :thumb => '100x100>' }
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  helper_method :has_avatar?
  # before_save :upload_images


  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || edit_user_registration_path
  end

  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :avatar)}
  end

  def has_avatar?
    current_user.avatar.file?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = current_user.pictures
  end

  def new
    @user = current_user
    @picture = Picture.new
  end

  def create
    @user = current_user

    @user.pictures.create(picture_params)

    redirect_to user_pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="hero">
  <h1 class="text-center">Let your photos Twinkl</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwinklPhotoSharing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='container'>
    <div id="user_nav">
      <%= link_to "Twinkl", root_path %>
      <% if current_user %>
        |
        <%= link_to "Upload Pictures", new_user_picture_path(current_user), class: "pull=left" %>
        |
        <%= link_to "My Pictures", user_pictures_path(current_user), class: "pull=left" %>
      <% end %>
      <%#= image_tag(current_user.avatar.url(:thumb)) %>
      <span class="pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit Profile', edit_user_registration_path %> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path %> |
          <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </span>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/pictures/index.html.erb
<h1>Your pictures!</h1>


<% @pictures.each do |picture| %>
  <%= image_tag picture.picture.url %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add your pictures.</h1>

<%= form_for [@user, @picture] do |f| %>
  <%#= file_field_tag "images[]", type: :file, multiple: true %>

  <%= f.file_field :picture %>
  <%= f.submit "Upload pictures" %>
<% end %>

app/views/users/new.html.erb
<h1>Picture List</h1>

<%= form_for @user, :url => root_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit "Submit" %>
<% end %>

<h3>Add a photo link</h3>

<%= image_tag @user.avatar.url %>